version: '3.8'
services: 
  database:
    image: mongo
    command: ["--bind_ip_all"]
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      -  mongodb:/data/db
      - ./database:/docker-entrypoint-initdb.d:ro
    ports:
      - '27017:27017'
  server:
    build:
      context: ./server
      target: dev
    volumes:
      - .:/src
    command: npm run start:dev
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
volumes:
  mongodb: