version: '3.7'
services: 
  database:
    image: mongo
    command: ["--bind_ip_all"]
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      -  mongodb:/data/db
      - ./database:/docker-entrypoint-initdb.d:ro
    ports:
      - '27017:27017'
volumes:
  mongodb: